// AUTO-GENERATED by scripts/extract-theme-palettes.cjs — do not edit manually.
// Representative color palette for each shiki bundled theme.
// Extracted from @shikijs/themes tokenColors + editor colors.
// Used by settings dropdown to show color swatches per theme.

export interface ThemePalette {
  bg: string
  fg: string
  keyword: string
  string: string
  func: string
  comment: string
}

export const THEME_PALETTES: Readonly<Record<string, ThemePalette>> = {
  "andromeeda": {
    "bg": "#23262E",
    "fg": "#D5CED9",
    "keyword": "#f39c12",
    "string": "#96E072",
    "func": "#FFE66D",
    "comment": "#A0A1A7cc"
  },
  "aurora-x": {
    "bg": "#07090F",
    "fg": "",
    "keyword": "#C792EA",
    "string": "#C3E88D",
    "func": "#82AAFF",
    "comment": "#546E7A"
  },
  "ayu-dark": {
    "bg": "#10141c",
    "fg": "#bfbdb6",
    "keyword": "#ff8f40",
    "string": "#aad94c",
    "func": "#ffb454",
    "comment": "#5a6673"
  },
  "ayu-light": {
    "bg": "#fcfcfc",
    "fg": "#5c6166",
    "keyword": "#fa8532",
    "string": "#86b300",
    "func": "#eba400",
    "comment": "#adaeb1"
  },
  "ayu-mirage": {
    "bg": "#242936",
    "fg": "#cccac2",
    "keyword": "#ffa659",
    "string": "#d5ff80",
    "func": "#ffcd66",
    "comment": "#6e7c8f"
  },
  "catppuccin-frappe": {
    "bg": "#303446",
    "fg": "#c6d0f5",
    "keyword": "#ef9f76",
    "string": "#a6d189",
    "func": "#8caaee",
    "comment": "#949cbb"
  },
  "catppuccin-latte": {
    "bg": "#eff1f5",
    "fg": "#4c4f69",
    "keyword": "#fe640b",
    "string": "#40a02b",
    "func": "#1e66f5",
    "comment": "#7c7f93"
  },
  "catppuccin-macchiato": {
    "bg": "#24273a",
    "fg": "#cad3f5",
    "keyword": "#f5a97f",
    "string": "#a6da95",
    "func": "#8aadf4",
    "comment": "#939ab7"
  },
  "catppuccin-mocha": {
    "bg": "#1e1e2e",
    "fg": "#cdd6f4",
    "keyword": "#fab387",
    "string": "#a6e3a1",
    "func": "#89b4fa",
    "comment": "#9399b2"
  },
  "dark-plus": {
    "bg": "#1E1E1E",
    "fg": "#D4D4D4",
    "keyword": "#b5cea8",
    "string": "#ce9178",
    "func": "#569cd6",
    "comment": "#6A9955"
  },
  "dracula-soft": {
    "bg": "#282A36",
    "fg": "#f6f6f4",
    "keyword": "#bf9eee",
    "string": "#e7ee98",
    "func": "#62e884",
    "comment": "#7b7f8b"
  },
  "dracula": {
    "bg": "#282A36",
    "fg": "#F8F8F2",
    "keyword": "#BD93F9",
    "string": "#F1FA8C",
    "func": "#50FA7B",
    "comment": "#6272A4"
  },
  "everforest-dark": {
    "bg": "#2d353b",
    "fg": "#d3c6aa",
    "keyword": "#e67e80",
    "string": "#dbbc7f",
    "func": "#a7c080",
    "comment": "#859289"
  },
  "everforest-light": {
    "bg": "#fdf6e3",
    "fg": "#5c6a72",
    "keyword": "#f85552",
    "string": "#dfa000",
    "func": "#8da101",
    "comment": "#939f91"
  },
  "github-dark-default": {
    "bg": "#0d1117",
    "fg": "#e6edf3",
    "keyword": "#ff7b72",
    "string": "#a5d6ff",
    "func": "#d2a8ff",
    "comment": "#8b949e"
  },
  "github-dark-dimmed": {
    "bg": "#22272e",
    "fg": "#adbac7",
    "keyword": "#f47067",
    "string": "#96d0ff",
    "func": "#dcbdfb",
    "comment": "#768390"
  },
  "github-dark-high-contrast": {
    "bg": "#0a0c10",
    "fg": "#f0f3f6",
    "keyword": "#ff9492",
    "string": "#addcff",
    "func": "#dbb7ff",
    "comment": "#bdc4cc"
  },
  "github-dark": {
    "bg": "#24292e",
    "fg": "#e1e4e8",
    "keyword": "#f97583",
    "string": "#9ecbff",
    "func": "",
    "comment": "#6a737d"
  },
  "github-light-default": {
    "bg": "#ffffff",
    "fg": "#1f2328",
    "keyword": "#cf222e",
    "string": "#0a3069",
    "func": "#8250df",
    "comment": "#6e7781"
  },
  "github-light-high-contrast": {
    "bg": "#ffffff",
    "fg": "#0e1116",
    "keyword": "#a0111f",
    "string": "#032563",
    "func": "#622cbc",
    "comment": "#66707b"
  },
  "github-light": {
    "bg": "#fff",
    "fg": "#24292e",
    "keyword": "#d73a49",
    "string": "#032f62",
    "func": "",
    "comment": "#6a737d"
  },
  "gruvbox-dark-hard": {
    "bg": "#1d2021",
    "fg": "#ebdbb2",
    "keyword": "#fb4934",
    "string": "#b8bb26",
    "func": "#fabd2f",
    "comment": "#928374"
  },
  "gruvbox-dark-medium": {
    "bg": "#282828",
    "fg": "#ebdbb2",
    "keyword": "#fb4934",
    "string": "#b8bb26",
    "func": "#fabd2f",
    "comment": "#928374"
  },
  "gruvbox-dark-soft": {
    "bg": "#32302f",
    "fg": "#ebdbb2",
    "keyword": "#fb4934",
    "string": "#b8bb26",
    "func": "#fabd2f",
    "comment": "#928374"
  },
  "gruvbox-light-hard": {
    "bg": "#f9f5d7",
    "fg": "#3c3836",
    "keyword": "#9d0006",
    "string": "#79740e",
    "func": "#b57614",
    "comment": "#928374"
  },
  "gruvbox-light-medium": {
    "bg": "#fbf1c7",
    "fg": "#3c3836",
    "keyword": "#9d0006",
    "string": "#79740e",
    "func": "#b57614",
    "comment": "#928374"
  },
  "gruvbox-light-soft": {
    "bg": "#f2e5bc",
    "fg": "#3c3836",
    "keyword": "#9d0006",
    "string": "#79740e",
    "func": "#b57614",
    "comment": "#928374"
  },
  "horizon-bright": {
    "bg": "#FDF0ED",
    "fg": "",
    "keyword": "#8A31B9",
    "string": "#F6661E",
    "func": "#1D8991",
    "comment": "#33333380"
  },
  "horizon": {
    "bg": "#1C1E26",
    "fg": "",
    "keyword": "#B877DBE6",
    "string": "#FAB795E6",
    "func": "#25B0BCE6",
    "comment": "#BBBBBB4D"
  },
  "houston": {
    "bg": "#17191e",
    "fg": "#eef0f9",
    "keyword": "#ffd493",
    "string": "#ffd493",
    "func": "#00daef",
    "comment": "#545864"
  },
  "kanagawa-dragon": {
    "bg": "#181616",
    "fg": "#C5C9C5",
    "keyword": "#8992A7",
    "string": "#8A9A7B",
    "func": "#8BA4B0",
    "comment": "#737C73"
  },
  "kanagawa-lotus": {
    "bg": "#F2ECBC",
    "fg": "#545464",
    "keyword": "#624C83",
    "string": "#6F894E",
    "func": "#4D699B",
    "comment": "#716E61"
  },
  "kanagawa-wave": {
    "bg": "#1F1F28",
    "fg": "#DCD7BA",
    "keyword": "#957FB8",
    "string": "#98BB6C",
    "func": "#7E9CD8",
    "comment": "#727169"
  },
  "laserwave": {
    "bg": "#27212e",
    "fg": "#ffffff",
    "keyword": "#40b4c4",
    "string": "#b4dce7",
    "func": "#EB64B9",
    "comment": "#91889b"
  },
  "light-plus": {
    "bg": "#FFFFFF",
    "fg": "#000000",
    "keyword": "#098658",
    "string": "#a31515",
    "func": "#0000ff",
    "comment": "#008000"
  },
  "material-theme-darker": {
    "bg": "#212121",
    "fg": "#EEFFFF",
    "keyword": "#F78C6C",
    "string": "#C3E88D",
    "func": "#EEFFFF",
    "comment": "#545454"
  },
  "material-theme-lighter": {
    "bg": "#FAFAFA",
    "fg": "#90A4AE",
    "keyword": "#F76D47",
    "string": "#91B859",
    "func": "#90A4AE",
    "comment": "#90A4AE"
  },
  "material-theme-ocean": {
    "bg": "#0F111A",
    "fg": "#babed8",
    "keyword": "#F78C6C",
    "string": "#C3E88D",
    "func": "#babed8",
    "comment": "#464B5D"
  },
  "material-theme-palenight": {
    "bg": "#292D3E",
    "fg": "#babed8",
    "keyword": "#F78C6C",
    "string": "#C3E88D",
    "func": "#babed8",
    "comment": "#676E95"
  },
  "material-theme": {
    "bg": "#263238",
    "fg": "#EEFFFF",
    "keyword": "#F78C6C",
    "string": "#C3E88D",
    "func": "#EEFFFF",
    "comment": "#546E7A"
  },
  "min-dark": {
    "bg": "#1f1f1f",
    "fg": "",
    "keyword": "#b392f0",
    "string": "#9db1c5",
    "func": "#f97583",
    "comment": "#6b737c"
  },
  "min-light": {
    "bg": "#ffffff",
    "fg": "#212121",
    "keyword": "#24292eff",
    "string": "#2b5581",
    "func": "#D32F2F",
    "comment": "#c2c3c5"
  },
  "monokai": {
    "bg": "#272822",
    "fg": "#f8f8f2",
    "keyword": "#F92672",
    "string": "#E6DB74",
    "func": "#A6E22E",
    "comment": "#88846f"
  },
  "night-owl-light": {
    "bg": "#FBFBFB",
    "fg": "#403f53",
    "keyword": "#5ca7e4",
    "string": "#4876d6",
    "func": "#994cc3",
    "comment": "#989fb1"
  },
  "night-owl": {
    "bg": "#011627",
    "fg": "#d6deeb",
    "keyword": "#5ca7e4",
    "string": "#ecc48d",
    "func": "#c792ea",
    "comment": "#637777"
  },
  "nord": {
    "bg": "#2e3440",
    "fg": "#d8dee9",
    "keyword": "#81A1C1",
    "string": "#A3BE8C",
    "func": "#88C0D0",
    "comment": "#616E88"
  },
  "one-dark-pro": {
    "bg": "#282c34",
    "fg": "#abb2bf",
    "keyword": "#c678dd",
    "string": "#98c379",
    "func": "#61afef",
    "comment": "#5c6370"
  },
  "one-light": {
    "bg": "#FAFAFA",
    "fg": "#383A42",
    "keyword": "#A626A4",
    "string": "#50A14F",
    "func": "#4078F2",
    "comment": "#A0A1A7"
  },
  "plastic": {
    "bg": "#21252B",
    "fg": "#A9B2C3",
    "keyword": "#E06C75",
    "string": "#98C379",
    "func": "#B57EDC",
    "comment": "#5F6672"
  },
  "poimandres": {
    "bg": "#1b1e28",
    "fg": "#a6accd",
    "keyword": "#5DE4c7c0",
    "string": "#5DE4c7",
    "func": "#ADD7FF",
    "comment": "#767c9dB0"
  },
  "red": {
    "bg": "#390000",
    "fg": "#F8F8F8",
    "keyword": "#f12727ff",
    "string": "#cd8d8dff",
    "func": "",
    "comment": "#e7c0c0ff"
  },
  "rose-pine-dawn": {
    "bg": "#faf4ed",
    "fg": "#575279",
    "keyword": "#286983",
    "string": "#ea9d34",
    "func": "",
    "comment": "#9893a5"
  },
  "rose-pine-moon": {
    "bg": "#232136",
    "fg": "#e0def4",
    "keyword": "#3e8fb0",
    "string": "#f6c177",
    "func": "",
    "comment": "#6e6a86"
  },
  "rose-pine": {
    "bg": "#191724",
    "fg": "#e0def4",
    "keyword": "#31748f",
    "string": "#f6c177",
    "func": "",
    "comment": "#6e6a86"
  },
  "slack-dark": {
    "bg": "#222222",
    "fg": "#E6E6E6",
    "keyword": "#569cd6",
    "string": "#ce9178",
    "func": "#DCDCAA",
    "comment": "#6A9955"
  },
  "slack-ochin": {
    "bg": "#FFF",
    "fg": "#000",
    "keyword": "#7b30d0",
    "string": "#a44185",
    "func": "#7eb233",
    "comment": "#357b42"
  },
  "snazzy-light": {
    "bg": "#FAFBFC",
    "fg": "#565869",
    "keyword": "#F767BB",
    "string": "#CF9C00",
    "func": "#09A1ED",
    "comment": "#ADB1C2"
  },
  "solarized-dark": {
    "bg": "#002B36",
    "fg": "#839496",
    "keyword": "#859900",
    "string": "#2AA198",
    "func": "#268BD2",
    "comment": "#586E75"
  },
  "solarized-light": {
    "bg": "#FDF6E3",
    "fg": "#657B83",
    "keyword": "#859900",
    "string": "#2AA198",
    "func": "#268BD2",
    "comment": "#93A1A1"
  },
  "synthwave-84": {
    "bg": "#262335",
    "fg": "",
    "keyword": "#72f1b8",
    "string": "#848bbd",
    "func": "#36f9f6",
    "comment": "#848bbd"
  },
  "tokyo-night": {
    "bg": "#1a1b26",
    "fg": "#a9b1d6",
    "keyword": "#5a638c",
    "string": "#9ece6a",
    "func": "#0db9d7",
    "comment": "#51597d"
  },
  "vesper": {
    "bg": "#101010",
    "fg": "#FFF",
    "keyword": "#A0A0A0",
    "string": "#99FFE4",
    "func": "#FFC799",
    "comment": "#8b8b8b94"
  },
  "vitesse-black": {
    "bg": "#000",
    "fg": "#dbd7cacc",
    "keyword": "#444444",
    "string": "#c98a7d",
    "func": "#80a665",
    "comment": "#758575dd"
  },
  "vitesse-dark": {
    "bg": "#121212",
    "fg": "#dbd7caee",
    "keyword": "#666666",
    "string": "#c98a7d",
    "func": "#80a665",
    "comment": "#758575dd"
  },
  "vitesse-light": {
    "bg": "#ffffff",
    "fg": "#393a34",
    "keyword": "#999999",
    "string": "#b56959",
    "func": "#59873a",
    "comment": "#a0ada0"
  }
}
